# Generated by Django 5.2.1 on 2025-06-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mydjango", "0002_post_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
