# Generated by Django 5.2.1 on 2025-06-19 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mydjango", "0003_post_image_post_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="topic",
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="mydjango.post",
            ),
        ),
    ]
